### PR TITLE
PYTHON-517 Update plugin.py to work with org repos (with git. in their name)

### PR DESCRIPTION
**Pull request by scr-oath**
## Description
Allow org pages to publish correctly

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **[CONTRIBUTING](./Contributing.md)** document.
- [ ] I have added tests to cover my changes.

## License

I confirm that this contribution is made under a Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by dwighthubbard — CHANGES_REQUESTED** [review]
The removesuffix() method was added in python 3.9.  Before we merge this the setup.cfg python_requires value should be set to `>=3.9` so this change doesn't break people using older python releases.

**Comment by scr-oath** [comment]
> The removesuffix() method was added in python 3.9. Before we merge this the setup.cfg python_requires value should be set to `>=3.9` so this change doesn't break people using older python releases.

Thanks - instead of this, I used re.sub, which has been there for quite some time, to replace the `\.git$` at the end of the url

**Comment by scr-oath** [comment]
> setup.cfg

Undid the re.sub solution and did this like you requested.

**Comment by dwighthubbard** [comment]
This functionality was merged into the project as part of a different PR.

**Pull request closed without merging**
